"""Add Softdelete

Revision ID: 27d376d56b88
Revises: 3772e1120e11
Create Date: 2025-08-18 17:28:39.551345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d376d56b88'
down_revision: Union[str, Sequence[str], None] = '3772e1120e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('state', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('tasks', 'delete_at')
    op.drop_column('tasks', 'update_at')
    op.drop_column('tasks', 'create_at')
    # ### end Alembic commands ###
